name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t test-image:latest .

    - name: List Docker images
      run: docker images

    - name: Set docker_credentials_present
      id: check-secrets
      run: |
        if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "present=true" >> $GITHUB_OUTPUT
        else
          echo "present=false" >> $GITHUB_OUTPUT
        fi

    - name: Login to Docker Hub
      if: steps.check-secrets.outputs.present == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: steps.check-secrets.outputs.present == 'true'
      run: |
        docker tag test-image:latest ${{ secrets.DOCKER_USERNAME }}/test-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/test-image:latest

