name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Usa tus runners auto-hospedados

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: List images (comprobación)
      run: docker images

    # Opcional: Publicar en Docker Hub
    - name: Login to Docker Hub
      if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
      run: |
        docker tag my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

